import React, { useContext } from "react"
import { Context, ContextProvider } from "../context/AppContextProvider"

import { Button } from "@mui/material"
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';



export default function About() {


    const { count, setCount } = useContext(Context)
    const router = useRouter();

    return (

        <>

            <Head>
                <title>About Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Link href="/Home"><h1>About page, go to Home {count}</h1></Link>
            <Button variant="contained" onClick={function () {
                setCount(pre => pre + 1)
            }}>add</Button>

            <br />
            <Button variant="contained" onClick={function () {
                router.push("/Home")
            }}>go to Home</Button>

        </>

    )
}