import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Button, Box } from "@mui/material"
import React, { useContext, useEffect } from "react"



import { AppContext } from "../context/AppContextProvider"

import Link from "next/link"
import axios from "axios"
import Router, { useRouter } from 'next/router';

import myImageSrc from "../public/vercel.svg";


// export async function getStaticPaths() {
//   return {
//     paths: [
//       { params: { ttt: 1 } }, { params: { ttt: 2 } }

//     ],
//     fallback: false // false or 'blocking'
//   };
// }

export async function getStaticProps(context) {


  //const { params, query } = context


  //console.log("HOME========", context)
  // const random = Math.random()
  // console.log(random)
  // if (random > 0.5) {

  
  //   return {
  //     redirect: {
  //       destination: '/api',
  //       permanent: false,
  //     },
  //   }
  // }


  return {
    props: {},
   // revalidate: 10
  }

}




export default function Home() {

  console.log("home")
  const { count, setCount } = useContext(AppContext)
  const router = useRouter();

  const myLoader = ({ src }) => {
    // return `${API}/user/photo/${blog.postedBy.username}`;
    return src
  }

  return (

    <div className={styles.container}>

      <Button onClick={function () {
        axios.delete("/api/usercookie").then(response => {

          //router.replace("/")

          Router.replace("/")
        })
      }}>Delete Cookie</Button>



      <Box sx={{//backgroundColor:"skyblue",
        position: "relative", width: "200px", height: "200px"
      }}>
        <Image loader={myLoader}
          src="https://wx3.sinaimg.cn/mw690/006nD01hgy1h1ls8p0fjoj32c02c04qq.jpg"
          placeholder='blur'
          alt="iiiaa"
          blurDataURL="https://picsum.photos/200/300"
          unoptimized
          // width={200}
          // height={600}
          // style={{backgroundColor: "pink"}}
          layout='fill'
          objectFit='cover'
          objectPosition='0px 0px'
          referrerPolicy='no-referrer'
        />
      </Box>
      <Image loader={myLoader}
        src="https://wx3.sinaimg.cn/mw690/006nD01hgy1h1ls8p0fjoj32c02c04qq.jpg"
        placeholder={"blur"}
        //  alt="iiiaa"
        blurDataURL="https://picsum.photos/200/300"
        unoptimized
        width={330}
        height={430}
        style={{ backgroundColor: "pink" }}
        objectFit='contain'
        objectPosition='0px 0px'
        referrerPolicy='no-referrer'
      />

      <Link href="/About"><h1>go to about {count}</h1></Link>
      <Button onClick={function () {
        setCount(pre => pre + 1)
      }}>add</Button>


      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              //src="../public/vercel.svg" // for export static page
              src="vercel.svg"
              loader={myLoader}
              placeholder='blur'
              blurDataURL="/"
              alt="Vercel Logo" width={72} height={16}
            />


            {/* <img src={ myImageSrc.src  } style={{width:100,height:100}} /> */}
            {/* <img src={"/vercel.svg"} style={{ width: 100, height: 100 }} /> */}
          </span>
        </a>
      </footer>


      {/* <img src="https://wx4.sinaimg.cn/mw690/006eW3CSly1h1mcu82qnsj322m340kjl.jpg"
        width={"100%"} height={"100%"} referrerPolicy='no-referrer' /> */}


    </div>

  )
}




